### ISSUE TITLE
7GPMWPME35L5C4J

### ISSUE THREAD

**Issue by MCampos92** [cris12gm/normSeq#1]
Hi I was trying to use normSeq to develop, normalisation of my data. My input file is the raw counts extracted from featureCounts, first column with the name of the genes and the others the raw counts of the sample.
I used the same format as the templastes but I get some error that I cannot see.

Thanks.
Miguel

**Comment by cris12gm** [comment]
Dear Miguel,

Thanks for using normSeq. I just looked at your job and it was a bug in our server that we just fixed, it should not happen again with future jobs but let us know if you have further problems. You can see the results now in the following link: https://arn.ugr.es/normSeq/results/?jobID=7GPMWPME35L5C4J

Sorry for the inconvenience.
Best,
Cristina

**Comment by MCampos92** [comment]
Thanks a lot, and great job with this tool!
Looks amazing.

Miguel
