### ISSUE TITLE
Error in job  7YQMKZ0004FA2PL

### ISSUE THREAD

**Issue by cobra1234-lab** [cris12gm/normSeq#10]

**Comment by cris12gm** [comment]
Dear @cobra1234-lab,

Thanks for using NormSeq and sorry for the delay in our answer.
There are some samples, for example, "25-Jan" that are in the annotation file but not included in the matrix file.
We will upgrade the software to deal with this issue, but to solve the problem please check that all samples included in the annotation file are also included in the matrix.

Best,
Cristina
