### ISSUE TITLE
Error in job

### ISSUE THREAD

**Issue by leocrc98** [cris12gm/normSeq#2]
Hey, 
I have an error in this job ID Q2J5T1EIJ77UNF9 and the page redirect me here. Someone knows how to help?
Regards

**Comment by cris12gm** [comment]
Dear @leocrc98 ,

Although you mentioned that this has been solved we manually fixed the files so you get the results here: https://arn.ugr.es/normSeq/results/?jobID=Q2J5T1EIJ77UNF9

Best,
Cristina
