### ISSUE TITLE
Error in job ID VY7E2FVC63CK6NZ

### ISSUE THREAD

**Issue by leocrc98** [cris12gm/normSeq#3]
I solved the problem, it was in the metradata file.
I got a local problem in this jobb ID VY7E2FVC63CK6NZ and I do not understand the error. Coould you please have a look?

**Comment by cris12gm** [comment]
Dear @leocrc98,

Thanks for using normSeq, and sorry for the inconvenience. It was an error in the website that has now been fixed, you can find your results here: https://arn.ugr.es/normSeq/results/?jobID=VY7E2FVC63CK6NZ
Please let us know if you have further problems.

Best,
Cristina
