### ISSUE TITLE
error in 9DWGB6WHEF48X9H

### ISSUE THREAD

**Issue by rgescudero** [cris12gm/normSeq#4]

**Comment by cris12gm** [comment]
Dear @rgescudero ,

Thanks for using NormSeq. I just looked at your job and it was a bug in our server that we just fixed, it should not happen again with future jobs but let us know if you have further problems.
Please note that differential expression analysis was not possible as only one of your groups has replicates, and the different software that is implemented in NormSeq needs at least two replicates per condition. 
You can see the results now in the following link: https://arn.ugr.es/normSeq/results/?jobID=9DWGB6WHEF48X9H

Sorry for the inconvenience.
Best,
Cristina

**Comment by rgescudero** [comment]
Thank you very much for the info. I will fix the error and try it again.
Ramon
